config/routes.rb
Swap::Application.routes.draw do

  scope :constraints => { :subdomain => ["", "www"] } do

    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :users, :controllers => {
        :omniauth_callbacks => 'users/omniauth_callbacks'
    }

    localized(I18n.available_locales) do

      resources :user_conversations, only: [:index, :show, :new, :create] do
        member do
          post :reply
          post :trash
          post :untrash
          post :new
        end
      end

      resources :users do
        resources :user_ratings
        collection do
          post 'fb_create'
          get 'settings'
        end
      end

      resources :courses do
        collection do
          get :show_past_courses
          post :new_with_request
          post :new_with_course
        end
        member do
          get :manage
          match 'manage/:course_member_id', :action => :manage
        end
      end

      resources :course_requests do
        collection do
          post :join
          post :disjoin
        end
      end

      resources :course_conversations

      resources :newsletter_subscribers do
        collection do
          get 'unsubscribe'
        end
      end

      resources :category_abonnements do
        collection do
          get 'find_categories'
        end
      end

      resources :newsletters

      resources :course_members do
        collection do
          post :new_request
          get :new_request
        end
      end

      resources :course_member_conversations do
        collection do
          post :reply
          post :host_reply
        end
      end

      resources :categories

      resource :mails

      get 'landingpage',  :to => 'pages#landingpage'
      get 'welcome',  :to => 'pages#welcome'
      get 'my_courses', :to => 'users#my_courses'
      get 'my_course_requests', :to => 'users#my_course_requests'

      get 'help',     :to => 'pages#help'
      get 'tips',     :to => 'pages#tips'
      get 'rules',    :to => 'pages#rules'
      get 'news',     :to => 'pages#news'
      get 'team',     :to => 'pages#team'
      get 'contact',  :to => 'pages#contact'
      get 'coverage', :to => 'pages#coverage'

      get 'about',    :to => 'pages#about'
      get 'imprint',  :to => 'pages#imprint'
      post 'contact_us',  :to => 'pages#contact_us'
    end

    unless Rails.application.config.consider_all_requests_local
      match '*not_found', to: 'errors#error_404'
    end

    root :to => 'pages#welcome'
  end

  scope :constraints => { :subdomain => "beta" } do

    root :to => 'pages#welcome', :constraints => {:subdomain => "www"}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include PaperclipProcessors::SharedMethods

  acts_as_messageable

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me,
                  :first_name, :last_name, :zip, :confirmed_at, :user_images_attributes,
                  :description, :skills, :job, :motivation, :birthday, :user_key,
                  :country, :city, :fb_user, :image, :crop_x, :crop_y, :crop_w, :crop_h

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :zip
  validates_presence_of :country
  validates_presence_of :city

#   validates_presence_of :user_key
#   if ActiveRecord::Base.connection.tables.include?("user_keys")
#     validates_inclusion_of :user_key, :in => UserKey.all.empty? ? [] : UserKey.all.collect{|i| i.key.to_s}.to_enum,  :message => "Dieser Code ist uns leider nicht bekannt"
#   end

  validates :zip, :numericality => { :only_integer => true }

  has_many :courses, :dependent => :destroy
  has_many :course_members, :through => :courses, :dependent => :destroy
  has_many :course_conversations, :dependent => :destroy
  has_many :category_abonnements, :dependent => :destroy
  has_many :user_ratings, :dependent => :destroy
  has_many :course_member_conversations, :dependent => :destroy

  has_many :course_request_users, :dependent => :destroy
  has_many :course_requests, :through => :course_request_users

  has_attached_file :image,
                    :styles => { :thumb => "46x46#", :xsmall => "32x32#", :small => "60x60#", :medium => "300x300#", :big => "800x800>" },
                    :processors => [:cropper],
                    :default_url => "/assets/user/:style.png"

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_image, :if => :cropping?

  validates_attachment_size :image, :less_than => 5.megabytes



  before_validation :set_city

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else
      user = User.new(:email => data.email,
                      :first_name => data.first_name,
                      :last_name => data.last_name,
                      :fb_user => true)
      user
    end
  end

  def has_course_request?(course_request)
    self.course_requests.find_by_id(course_request.id) ? true : false
  end

  def join_course_request(course_request)
    self.has_course_request?(course_request) ? false : self.course_requests << course_request
  end

  def disjoin_course_request(course_request)
    if CourseRequest.find_by_id(course_request.id).users.count > 1
      self.course_requests.delete(course_request)
    else
      CourseRequest.find_by_id(course_request.id).destroy if self.has_course_request?(course_request)
    end
  end

  def get_age
    now = Time.now.utc.to_date
    age = now.year - self.birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0) unless self.birthday.nil?
    age
  end

  def get_courses
    self.courses.where("date > #{Time.now.to_date}")
  end

  def get_old_courses
    Course.unscoped.find(:all, :conditions => ["date < ? && user_id = ?",Time.now.to_date, self.id ] )
  end

  def get_enquired_courses
    get_course_memberships.map{|i| i.course}
  end

  def get_course_requests
    self.course_requests
  end

  def get_course_memberships
    cms = CourseMember.find_all_by_user_id(self.id)
    cms.reject!{|cm| cm.course.nil?}.reject!{|cm| cm.course.date < Time.now } unless cms.blank?   #
    cms
  end

  def toggle_category_abonnements category
    if category_abonnement = self.category_abonnements.find_by_category_id(category.id)
      category_abonnement.destroy
    else
      self.category_abonnements.create(:category => category)
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(object)
    self.push_message
    email
  end

  def get_unread_message_count
    self.receipts.reject{|i| i.read}.count
  end

  def get_courses_requests_count
    self.courses.sum{|c| c.get_course_request_count}
  end

  def get_course_members
    CourseMember.find_all_by_course_id(self.courses.collect{|course| course.id})
  end

  def get_unread_course_member_conversations course_members
    return nil if course_members.empty?
    cmc = course_members.collect{|cm| cm.course_member_conversations}.flatten
    cmc.empty? ? nil : cmc.reject{|cmc| cmc.user == self || cmc.unread == false}
  end

  def get_unread_course_member_conversations_count
    cmc = []
    cmc << get_unread_course_member_conversations(get_course_members) << get_unread_course_member_conversations(get_course_memberships)
    cmc.flatten!
    cmc.reject!{|i| i.nil? }
    cmc.empty? ? 0 : cmc.count
  end

  def get_notification_count
    get_unread_message_count +
    get_courses_requests_count +
    get_unread_course_member_conversations_count
  end

  def courses_organized_counter
    counter = 0
    courses = Course.unscoped.find(:all, :conditions => ["date < ? && user_id = ?", Time.now, self.id])
    courses.each do |f|
      if f.course_members.count > 0
        counter += 1
      end
    end
    counter
  end

  def courses_attended_counter
    counter = 0
    self.course_members.each do |f|
      if f.course.date < Time.now
        counter += 1
      end
    end
    counter
  end

  def push_message
    begin
      Pusher["#{self.id}"].trigger('counter', {:message => self.get_notification_count.to_s})
    rescue Pusher::Error => e
      #TODO handle Pusher Error
    end
  end

  private

  def set_city
    location = Location.find_by_country_and_zip_code(self.country, self.zip)
    self.city = location.nil? ? "n/a" : location.city
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:info] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook", :name => @user.first_name
      sign_in_and_redirect @user, :event => :authentication
    else
      render :template => "users/complete_registration", :locals => {:user => @user}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:facebook, :fb_create] , :only => [:edit, :update, :settings, :my_courses, :my_course_requests, :my_conversations]
  before_filter :get_user, :only => [:edit, :update, :settings, :my_courses, :my_course_requests]

  def my_courses
  end

  def my_course_requests
  end

  def show
    @user = User.find(params[:id])
    @rating = @user.user_ratings.build
  end

  def edit
  end

  def settings
  end

  def update
    @user.update_attributes(params[:user])
    if @user.valid?
      @user.save!
      flash[:info] = I18n.t('msg.success')
      if params[:user][:image].blank? || params[:javascript].blank?
        redirect_to user_path(@user)
      else
        render "shared/crop", :locals => {:obj => @user}
      end
    else
      flash[:error] = I18n.t('msg.fail')
      redirect_to user_path(@user)
    end
  end


  def fb_create
    @user = User.new(params[:user])
    @user.password = Devise.friendly_token[0,20]
    unless @user.valid?
      render :complete_registration
    else
      flash[:info] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook", :name => @user.first_name
      #@user.confirm!
      @user.save!
      sign_in_and_redirect @user, :event => :authentication
    end
  end

  private

  def get_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show/_course.html.haml
%article.begegnung

  %section.description
    %h2= link_to truncate(course.title, :length => 17, :omission => '..'), course_path(course)
    %p= I18n.localize(course.date, :format => :day) unless course.date.nil?
    %p= "in #{truncate(course.city, :length => 17, :omission => '..') unless course.city.nil?}"
  = link_to image_tag(coursepic(course, :xsmall), :size => '100x100'), course_path(course)

app/views/users/show/_course_request.html.haml
%article.begegnungswunsch
  %section.description
    %h2= link_to truncate(course_request.title, :length => 17, :omission => '..'), course_request_path(course_request)

app/views/users/show/_old_course.html.haml
%article.begegnungswunsch
  %section.description
    %h2= link_to truncate(old_course.title, :length => 17, :omission => '..'), course_path(old_course)

app/views/users/show/_rating.html.haml
.rating-item
  - rating_user = User.find_by_id(rating.evaluator_id)
  = link_to image_tag(userpic(rating_user, :medium), :alt => username(rating_user), :size => '60x60'), user_path(rating_user)
  .header
    %p{:class => rating.rating}= rating.rating
    %p
      = I18n.localize(rating.created_at, :format => :day) unless rating.created_at.nil?
      von
      = link_to username(rating_user), user_path(rating_user)
  .clr
  .body
    %p.small= rating.body
.clr

app/views/users/show/_ratings.de.html.haml
= javascript_include_tag 'rails.validations'
= form_for [user,rating], :validate => true do |f|

  %fieldset
    %legend
      %strong Neue Bewertung abgeben:
    %div
      = f.label :rating
      %button.form-submit.form-nextstep.right{:style => 'width: 263px'}
        Bewertung abgeben
        %span
      .rating
        = f.select :rating, options_for_select(["positiv","neutral","negativ"]), :include_blank => true
      .clr

    %div
      = f.label :body
      .body
        = f.text_area :body

  %fieldset
    %legend
      %strong Bisherige Bewertungen:
    = render(:partial => 'users/show/rating', :collection => user.user_ratings.reject{|i| i.id.nil?}) || "noch keine"

app/views/users/show/_sidebar.de.html.haml
%article.side
  %figure.fancyimg
    %a{:href => userpic(user, :big), :class => 'pic', :rel => 'alternate'}
      = image_tag userpic(user, :medium), :alt => username(user), :size => '300x300'
      %span

  .clr
  %ul.userinfo
    %li
      %span Ausbildung
      %span{:title => safe_output(user.job)}= truncate(safe_output(user.job), :length => 45, :omission => '..')
    %li
      %span Alter
      %span= safe_output(user.get_age)
    %li
      %span Wohnort
      %span= safe_output(user.city)

  %h2 Begegnungen
  %ul.facts
    %li.course_client_count
      %span
      = "#{courses_attended(user)} Teilgenommen"
    %li.course_host_count
      %span
      = "#{courses_organized(user)} Gehalten"

  %h2 Bewertungen
  %ul.rating
    %li.rating-pos
      %span= user.rating_pos_count
      Positiv
    %li.rating-neut
      %span= user.rating_neut_count
      Neutral
    %li.rating-neg
      %span=user.rating_neg_count
      Negativ
  .clr

  - unless controller?("user_conversations") && !signed_in?
    %br
    = form_tag(new_user_conversation_path, :method => :post) do
      = hidden_field_tag :recipient_id, user.id
      %button.form-msg.form-submit{:style => 'width: 100%'}
        Nachricht senden
        %span
    = form_tag(new_user_conversation_path, :method => :post) do
      = hidden_field_tag :recipient_id, 0
      = hidden_field_tag :subject, "User: #{user.first_name} mit der id #{user.id}"
      = hidden_field_tag :body, "User wurde auffällig durch: "
      %button.form-button-petrol.form-submit{:style => 'width: 36px; height: 36px; font-size: 24px; line-height: 30px; margin-top: 10px', :onclick => "return confirm('Willst du diesen Benutzer wirklich melden?')" }
        !
        %span