config/routes.rb
Swap::Application.routes.draw do

  scope :constraints => { :subdomain => ["", "www"] } do

    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :users, :controllers => {
        :omniauth_callbacks => 'users/omniauth_callbacks'
    }

    localized(I18n.available_locales) do

      resources :user_conversations, only: [:index, :show, :new, :create] do
        member do
          post :reply
          post :trash
          post :untrash
          post :new
        end
      end

      resources :users do
        resources :user_ratings
        collection do
          post 'fb_create'
          get 'settings'
        end
      end

      resources :courses do
        collection do
          get :show_past_courses
          post :new_with_request
          post :new_with_course
        end
        member do
          get :manage
          match 'manage/:course_member_id', :action => :manage
        end
      end

      resources :course_requests do
        collection do
          post :join
          post :disjoin
        end
      end

      resources :course_conversations

      resources :newsletter_subscribers do
        collection do
          get 'unsubscribe'
        end
      end

      resources :category_abonnements do
        collection do
          get 'find_categories'
        end
      end

      resources :newsletters

      resources :course_members do
        collection do
          post :new_request
          get :new_request
        end
      end

      resources :course_member_conversations do
        collection do
          post :reply
          post :host_reply
        end
      end

      resources :categories

      resource :mails

      get 'landingpage',  :to => 'pages#landingpage'
      get 'welcome',  :to => 'pages#welcome'
      get 'my_courses', :to => 'users#my_courses'
      get 'my_course_requests', :to => 'users#my_course_requests'

      get 'help',     :to => 'pages#help'
      get 'tips',     :to => 'pages#tips'
      get 'rules',    :to => 'pages#rules'
      get 'news',     :to => 'pages#news'
      get 'team',     :to => 'pages#team'
      get 'contact',  :to => 'pages#contact'
      get 'coverage', :to => 'pages#coverage'

      get 'about',    :to => 'pages#about'
      get 'imprint',  :to => 'pages#imprint'
      post 'contact_us',  :to => 'pages#contact_us'
    end

    unless Rails.application.config.consider_all_requests_local
      match '*not_found', to: 'errors#error_404'
    end

    root :to => 'pages#welcome'
  end

  scope :constraints => { :subdomain => "beta" } do

    root :to => 'pages#welcome', :constraints => {:subdomain => "www"}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include PaperclipProcessors::SharedMethods

  acts_as_messageable

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me,
                  :first_name, :last_name, :zip, :confirmed_at, :user_images_attributes,
                  :description, :skills, :job, :motivation, :birthday, :user_key,
                  :country, :city, :fb_user, :image, :crop_x, :crop_y, :crop_w, :crop_h

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :zip
  validates_presence_of :country
  validates_presence_of :city

#   validates_presence_of :user_key
#   if ActiveRecord::Base.connection.tables.include?("user_keys")
#     validates_inclusion_of :user_key, :in => UserKey.all.empty? ? [] : UserKey.all.collect{|i| i.key.to_s}.to_enum,  :message => "Dieser Code ist uns leider nicht bekannt"
#   end

  validates :zip, :numericality => { :only_integer => true }

  has_many :courses, :dependent => :destroy
  has_many :course_members, :through => :courses, :dependent => :destroy
  has_many :course_conversations, :dependent => :destroy
  has_many :category_abonnements, :dependent => :destroy
  has_many :user_ratings, :dependent => :destroy
  has_many :course_member_conversations, :dependent => :destroy

  has_many :course_request_users, :dependent => :destroy
  has_many :course_requests, :through => :course_request_users

  has_attached_file :image,
                    :styles => { :thumb => "46x46#", :xsmall => "32x32#", :small => "60x60#", :medium => "300x300#", :big => "800x800>" },
                    :processors => [:cropper],
                    :default_url => "/assets/user/:style.png"

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_image, :if => :cropping?

  validates_attachment_size :image, :less_than => 5.megabytes



  before_validation :set_city

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else
      user = User.new(:email => data.email,
                      :first_name => data.first_name,
                      :last_name => data.last_name,
                      :fb_user => true)
      user
    end
  end

  def has_course_request?(course_request)
    self.course_requests.find_by_id(course_request.id) ? true : false
  end

  def join_course_request(course_request)
    self.has_course_request?(course_request) ? false : self.course_requests << course_request
  end

  def disjoin_course_request(course_request)
    if CourseRequest.find_by_id(course_request.id).users.count > 1
      self.course_requests.delete(course_request)
    else
      CourseRequest.find_by_id(course_request.id).destroy if self.has_course_request?(course_request)
    end
  end

  def get_age
    now = Time.now.utc.to_date
    age = now.year - self.birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0) unless self.birthday.nil?
    age
  end

  def get_courses
    self.courses.where("date > #{Time.now.to_date}")
  end

  def get_old_courses
    Course.unscoped.find(:all, :conditions => ["date < ? && user_id = ?",Time.now.to_date, self.id ] )
  end

  def get_enquired_courses
    get_course_memberships.map{|i| i.course}
  end

  def get_course_requests
    self.course_requests
  end

  def get_course_memberships
    cms = CourseMember.find_all_by_user_id(self.id)
    cms.reject!{|cm| cm.course.nil?}.reject!{|cm| cm.course.date < Time.now } unless cms.blank?   #
    cms
  end

  def toggle_category_abonnements category
    if category_abonnement = self.category_abonnements.find_by_category_id(category.id)
      category_abonnement.destroy
    else
      self.category_abonnements.create(:category => category)
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(object)
    self.push_message
    email
  end

  def get_unread_message_count
    self.receipts.reject{|i| i.read}.count
  end

  def get_courses_requests_count
    self.courses.sum{|c| c.get_course_request_count}
  end

  def get_course_members
    CourseMember.find_all_by_course_id(self.courses.collect{|course| course.id})
  end

  def get_unread_course_member_conversations course_members
    return nil if course_members.empty?
    cmc = course_members.collect{|cm| cm.course_member_conversations}.flatten
    cmc.empty? ? nil : cmc.reject{|cmc| cmc.user == self || cmc.unread == false}
  end

  def get_unread_course_member_conversations_count
    cmc = []
    cmc << get_unread_course_member_conversations(get_course_members) << get_unread_course_member_conversations(get_course_memberships)
    cmc.flatten!
    cmc.reject!{|i| i.nil? }
    cmc.empty? ? 0 : cmc.count
  end

  def get_notification_count
    get_unread_message_count +
    get_courses_requests_count +
    get_unread_course_member_conversations_count
  end

  def courses_organized_counter
    counter = 0
    courses = Course.unscoped.find(:all, :conditions => ["date < ? && user_id = ?", Time.now, self.id])
    courses.each do |f|
      if f.course_members.count > 0
        counter += 1
      end
    end
    counter
  end

  def courses_attended_counter
    counter = 0
    self.course_members.each do |f|
      if f.course.date < Time.now
        counter += 1
      end
    end
    counter
  end

  def push_message
    begin
      Pusher["#{self.id}"].trigger('counter', {:message => self.get_notification_count.to_s})
    rescue Pusher::Error => e
      #TODO handle Pusher Error
    end
  end

  private

  def set_city
    location = Location.find_by_country_and_zip_code(self.country, self.zip)
    self.city = location.nil? ? "n/a" : location.city
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:info] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook", :name => @user.first_name
      sign_in_and_redirect @user, :event => :authentication
    else
      render :template => "users/complete_registration", :locals => {:user => @user}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:facebook, :fb_create] , :only => [:edit, :update, :settings, :my_courses, :my_course_requests, :my_conversations]
  before_filter :get_user, :only => [:edit, :update, :settings, :my_courses, :my_course_requests]

  def my_courses
  end

  def my_course_requests
  end

  def show
    @user = User.find(params[:id])
    @rating = @user.user_ratings.build
  end

  def edit
  end

  def settings
  end

  def update
    @user.update_attributes(params[:user])
    if @user.valid?
      @user.save!
      flash[:info] = I18n.t('msg.success')
      if params[:user][:image].blank? || params[:javascript].blank?
        redirect_to user_path(@user)
      else
        render "shared/crop", :locals => {:obj => @user}
      end
    else
      flash[:error] = I18n.t('msg.fail')
      redirect_to user_path(@user)
    end
  end


  def fb_create
    @user = User.new(params[:user])
    @user.password = Devise.friendly_token[0,20]
    unless @user.valid?
      render :complete_registration
    else
      flash[:info] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook", :name => @user.first_name
      #@user.confirm!
      @user.save!
      sign_in_and_redirect @user, :event => :authentication
    end
  end

  private

  def get_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete.html.haml
%h2
  Daten verfollständigen
= form_for @user, :url =>  user_fb_create_path, :html => { :class => 'form-horizontal' } do |f|

  %fieldset
    = f.hidden_field :first_name
    = f.hidden_field :last_name
    = f.hidden_field :email
    = f.hidden_field :password

    %div.control-group{ :class => form_status(@user, :zip) }
      = f.label :zip, :class => 'control-label'
      .controls
        = f.text_field :zip
        %span.help-inline=  form_status_msg(@user, :zip)

  %div.form-actions
    = link_to "Registrierung abbrechen", root_path, :class => 'btn'
    = f.submit "Weiter", :class => 'btn-primary'

app/views/users/complete_registration.de.html.haml
= javascript_include_tag 'rails.validations'

%h2 Registrierung vervollständigen
= form_for @user, :validate => true, :url => fb_create_users_path, :html => { :class => 'form-horizontal' } do |f|

  %fieldset
    = f.hidden_field :first_name
    = f.hidden_field :last_name
    = f.hidden_field :email
    = f.hidden_field :password
    = f.hidden_field :fb_user
    %div
      = f.label :user_key
      .user_key
        = f.text_field :user_key, :style => 'width: 100%;'
        %p.small
          = "Wenn Du noch keinen Code besitzt, fordere bitte einfach einen über "
          = mail_to 'info@wissenteilen.com', nil, :subject => "Ich will einen Beta Code"
          = " an!"

    %div
      = f.label :location
      .location
        = f.select :country, options_for_select([["Österreich", "AT"], ["Deutschland", "DE"], ["Schweiz", "CH"]])
        PLZ:
        = f.text_field :zip

    .clr
    %button.form-submit.form-nextstep.right
      Registrierung abschließen
      %span

app/views/users/complete_registration.html.haml
= javascript_include_tag 'rails.validations'

%h2= I18n.t('devise.complete_registration.title')
= form_for @user, :validate => true, :url => fb_create_users_path, :html => { :class => 'form-horizontal' } do |f|

  %fieldset
    = f.hidden_field :first_name
    = f.hidden_field :last_name
    = f.hidden_field :email
    = f.hidden_field :password

    %div
      = f.label :zip
      = f.text_field :zip

  %div.form-actions
    = link_to I18n.t('devise.complete_registration.cancel'), root_path, :class => 'btn'
    = f.submit I18n.t('devise.complete_registration.submit'), :class => 'btn-primary'

app/views/users/edit.de.html.haml
= javascript_include_tag 'rails.validations', 'spin'


%h1 Benutzer bearbeiten
= form_for(@user, :validate => true, :html => { :method => :put, :multipart => true}) do |f|
  %fieldset
    %legend
      %strong Grundlegende Informationen:
    %div
      = f.label :first_name
      = f.text_field :first_name

    %div
      = f.label :last_name
      = f.text_field :last_name

    %div
      = f.label "Geburtstag"
      = f.date_select :birthday, :order => [:day, :month, :year], :include_blank => true, :start_year => 1900

    %div
      = f.label :location
      .location
        = f.select :country, options_for_select([["Österreich", "AT"], ["Deutschland", "DE"], ["Schweiz", "CH"]], @user.country)
        PLZ:
        = f.text_field :zip

  %fieldset
    %legend
      %strong Profilbild

    %div
      = f.label :image
      = f.file_field :image
      -unless @user.image.nil?
        %strong Aktuelles Bild 
        = image_tag userpic(@user, :thumb)
      

  %fieldset
    %legend
      %strong Über mich
    %div
      = f.label :description
      = f.text_area :description

    %div
      = f.label "Ausbildung"
      = f.text_field :job

    %div
      = f.label "warum bin ich auf wissen • teilen • können?"
      = f.text_area :motivation

    %div
      = f.label "hobbies und fähigkeiten"
      = f.text_area :skills

    %button#form-submit.form-submit.form-nextstep.right
      Profil speichern
      %span

:javascript
  $('#edit_user_#{@user.id}').prepend('#{hidden_field_tag 'javascript', 'true'}')

app/views/users/my_course_requests.de.html.haml
%section.detail
  = render :partial => '/users/shared/user_sidebar', :locals => { :user => @user }
  %article.main
    %section.overview
      = render :partial => '/users/shared/overview_header'
      %section.overview-main
        %h3 Eigene Wünsche
        = render(:partial => 'users/overview/course_request', :collection => @user.get_course_requests) || "keine"

        %br
        %a.form-button-petrol.form-nextstep{:href => url_for(new_course_request_path), :style => 'width: 400px; margin: 0 auto;'}
          Neuen Begegnungswunsch erstellen
          %span

app/views/users/my_courses.de.html.haml
%section.detail
  = render :partial => '/users/shared/user_sidebar', :locals => { :user => @user }
  %article.main
    %section.overview
      = render :partial => '/users/shared/overview_header'
      %section.overview-main
        %h3 Eigene Begegnungen
        = render(:partial => 'users/overview/course', :collection => @user.get_courses, :locals => { :manage_path => 'course' }) || "keine"

        %h3 Andere Begegnungen
        = render(:partial => 'users/overview/course', :collection => @user.get_enquired_courses, :locals => { :manage_path => 'course_member' }) || "keine"

        %br
        %a.form-button-petrol.form-nextstep{:href => url_for(new_course_path), :style => 'width: 300px; margin: 0 auto;'}
          Neue Begegnung erstellen
          %span

app/views/users/settings.de.html.haml
= javascript_include_tag 'rails.validations'

%h2 Einstellungen ändern


= link_to 'Benutzer löschen', registration_path(current_user), :confirm => 'Sind Sie sicher? Ihr Benutzerkonto wird unwiederruflich gelöscht', :method => :delete, :class => 'form-button-petrol'

app/views/users/show.de.html.haml
%section.detail
  %article.main
    %h1= username(@user)
    = render :partial => '/shared/social_media_like_buttons', :locals => { :special_url => request.original_url}
    %h2 Selbstbeschreibung
    %p= simple_format (@user.description) || "noch nicht ausgefüllt"
    %h2 Warum bin ich auf Wissen • Teilen • Können?
    %p= simple_format (@user.motivation) || "noch nicht ausgefüllt"
    %h2 Hobbies und Fähigkeiten
    %p= simple_format (@user.skills) || "noch nicht ausgefüllt"


    .user-courses
      %h2 Aktuelle Begegnungen
      = render(:partial => 'users/show/course', :collection => @user.get_courses) || "keine"
      .clr
    .user-course-requests
      %h2 Begegnungswünsche
      = render(:partial => 'users/show/course_request', :collection => @user.get_course_requests) || "keine"
      .clr
    .user-course-requests
      %h2 Bereits stattgefundene Begegnungen
      = render(:partial => 'users/show/old_course', :collection => @user.get_old_courses) || "keine"
      .clr
    .clr

    %section.bewertungen
      %h2 Bewertungen
      %ul.rating
        %li.rating-pos
          %span= @user.rating_pos_count
          Positiv
        %li.rating-neut
          %span= @user.rating_neut_count
          Neutral
        %li.rating-neg
          %span=@user.rating_neg_count
          Negativ
      .clr
      %br
      -if signed_in? && current_user != @user
        =render :partial => '/users/show/ratings', :locals => { :user => @user, :rating => @rating }

  = render :partial => '/users/show/sidebar', :locals => { :user => @user }