config/routes.rb
Swap::Application.routes.draw do

  scope :constraints => { :subdomain => ["", "www"] } do

    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :users, :controllers => {
        :omniauth_callbacks => 'users/omniauth_callbacks'
    }

    localized(I18n.available_locales) do

      resources :user_conversations, only: [:index, :show, :new, :create] do
        member do
          post :reply
          post :trash
          post :untrash
          post :new
        end
      end

      resources :users do
        resources :user_ratings
        collection do
          post 'fb_create'
          get 'settings'
        end
      end

      resources :courses do
        collection do
          get :show_past_courses
          post :new_with_request
          post :new_with_course
        end
        member do
          get :manage
          match 'manage/:course_member_id', :action => :manage
        end
      end

      resources :course_requests do
        collection do
          post :join
          post :disjoin
        end
      end

      resources :course_conversations

      resources :newsletter_subscribers do
        collection do
          get 'unsubscribe'
        end
      end

      resources :category_abonnements do
        collection do
          get 'find_categories'
        end
      end

      resources :newsletters

      resources :course_members do
        collection do
          post :new_request
          get :new_request
        end
      end

      resources :course_member_conversations do
        collection do
          post :reply
          post :host_reply
        end
      end

      resources :categories

      resource :mails

      get 'landingpage',  :to => 'pages#landingpage'
      get 'welcome',  :to => 'pages#welcome'
      get 'my_courses', :to => 'users#my_courses'
      get 'my_course_requests', :to => 'users#my_course_requests'

      get 'help',     :to => 'pages#help'
      get 'tips',     :to => 'pages#tips'
      get 'rules',    :to => 'pages#rules'
      get 'news',     :to => 'pages#news'
      get 'team',     :to => 'pages#team'
      get 'contact',  :to => 'pages#contact'
      get 'coverage', :to => 'pages#coverage'

      get 'about',    :to => 'pages#about'
      get 'imprint',  :to => 'pages#imprint'
      post 'contact_us',  :to => 'pages#contact_us'
    end

    unless Rails.application.config.consider_all_requests_local
      match '*not_found', to: 'errors#error_404'
    end

    root :to => 'pages#welcome'
  end

  scope :constraints => { :subdomain => "beta" } do

    root :to => 'pages#welcome', :constraints => {:subdomain => "www"}
  end
end

app/views/shared/_begegnung.html.haml
%article.begegnung#begegnung-new
  %p.begegnung-text= link_to image_tag('begegnungen/layout-begegnung-new.png', :alt => 'Neue Begegnung erstellen'), new_course_path, :class => 'begegnung-pic'
  %p.begegnung-text
    = link_to 'Neue Begegnung', new_course_path, :class => 'form-button-petrol'
    Du möchtest dein Talent oder deine Idee mit anderen teilen? Dann erstelle jetzt eine Begegnung. In 3 einfachen Schritten geht's los ...
    %br
    = link_to 'Neue Begegnung', new_course_path

app/views/shared/_begegnung_new.html.haml
%article.begegnung#begegnung-new
  %p.begegnung-text= link_to image_tag('begegnungen/layout-begegnungswunsch-new.png', :alt => 'Neuen Begegnungswunsch erstellen'), new_course_request_path, :class => 'begegnung-pic'
  %p.begegnung-text
    = link_to 'Neuer Wunsch', new_course_request_path, :class => 'form-button-petrol'
    Für dich war hier nichts dabei? Dann ergreif du doch Initiative und erstelle einen Wunsch. Vielleicht meldet sich schon bald jemand bei dir.
    %br
    = link_to 'Neuer Begegnungswunsch', new_course_request_path

app/views/shared/_categories.html.haml
%ul#begegnungssearch
  - Category.all.each do |cat|
    %li= link_to simple_format(cat.title.gsub(" ", "<br>")), find_categories_category_abonnements_path(:category => cat.id), :id => "cat-#{cat.id}", :remote => true, :class => "#{ (categories[cat.title].to_s == "0") ? 'category_link active' : 'category_link' }" 

app/views/shared/_search.html.haml
%ul#begegnungssearch
  - Category.all.each do |cat|
    %li= link_to simple_format(cat.title.gsub(" ", "<br>")), find_categories_category_abonnements_path(:category => cat.id, :controller_type => @current_controller), :id => "cat-#{cat.id}", :remote => true, :class => "#{(categories[cat.title].to_s == "0") ? 'category_link active' : 'category_link' }" 

  /*= form_tag @current_controller, :method => :get do*/
  /*  = text_field_tag('form-input-location', 'Puch bei Hallein', :class => 'form-input-full')*/
  /*  .submit-field-icon*/
  /*    = submit_tag (@current_controller == 'courses') ? 'Begegnung suchen' : 'Begegnungswunsch suchen', :class => 'form-submit', :id => 'form-submit-search'*/
  /*    %span*/

app/views/shared/_social_media_like_buttons.html.haml
.social-media-buttons
  #fb-root
  .g-plusone{ 'data-size' => 'small' }
  .fb-like{ 'data-href' => special_url.nil? ? 'https://www.facebook.com/wissenteilen' : special_url, 'data-send' => 'true', 'data-layout' => 'button_count', 'data-width' => '180', 'data-show-faces' => 'false'}

  :javascript
    window.___gcfg = {lang: 'de'};

    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1&appId=234910589931839";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

app/views/shared/crop.html.erb
<% content_for(:head) do %>
<%= stylesheet_link_tag "jquery.Jcrop.min" %>
<%= javascript_include_tag "jquery.Jcrop.min", "spin" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 200, 200],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 200/coords.w;
  var ry = 200/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= obj.image_geometry(:big).width %>) + 'px',
    height: Math.round(ry * <%= obj.image_geometry(:big).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= obj.image_geometry(:original).width %> / <%= obj.image_geometry(:big).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag obj.image.url(:big), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:200px; height:200px; overflow:hidden">
  <%= image_tag obj.image.url(:big), :id => "preview" %>
</div>

<%= form_for obj do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <div class="send-button">
    <button class="form-submit form-nextstep" id="form-submit">
      Bild zuschneiden
    </button>
    <span></span>
  </div>
<% end %>