config/routes.rb
Swap::Application.routes.draw do

  scope :constraints => { :subdomain => ["", "www"] } do

    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :users, :controllers => {
        :omniauth_callbacks => 'users/omniauth_callbacks'
    }

    localized(I18n.available_locales) do

      resources :user_conversations, only: [:index, :show, :new, :create] do
        member do
          post :reply
          post :trash
          post :untrash
          post :new
        end
      end

      resources :users do
        resources :user_ratings
        collection do
          post 'fb_create'
          get 'settings'
        end
      end

      resources :courses do
        collection do
          get :show_past_courses
          post :new_with_request
          post :new_with_course
        end
        member do
          get :manage
          match 'manage/:course_member_id', :action => :manage
        end
      end

      resources :course_requests do
        collection do
          post :join
          post :disjoin
        end
      end

      resources :course_conversations

      resources :newsletter_subscribers do
        collection do
          get 'unsubscribe'
        end
      end

      resources :category_abonnements do
        collection do
          get 'find_categories'
        end
      end

      resources :newsletters

      resources :course_members do
        collection do
          post :new_request
          get :new_request
        end
      end

      resources :course_member_conversations do
        collection do
          post :reply
          post :host_reply
        end
      end

      resources :categories

      resource :mails

      get 'landingpage',  :to => 'pages#landingpage'
      get 'welcome',  :to => 'pages#welcome'
      get 'my_courses', :to => 'users#my_courses'
      get 'my_course_requests', :to => 'users#my_course_requests'

      get 'help',     :to => 'pages#help'
      get 'tips',     :to => 'pages#tips'
      get 'rules',    :to => 'pages#rules'
      get 'news',     :to => 'pages#news'
      get 'team',     :to => 'pages#team'
      get 'contact',  :to => 'pages#contact'
      get 'coverage', :to => 'pages#coverage'

      get 'about',    :to => 'pages#about'
      get 'imprint',  :to => 'pages#imprint'
      post 'contact_us',  :to => 'pages#contact_us'
    end

    unless Rails.application.config.consider_all_requests_local
      match '*not_found', to: 'errors#error_404'
    end

    root :to => 'pages#welcome'
  end

  scope :constraints => { :subdomain => "beta" } do

    root :to => 'pages#welcome', :constraints => {:subdomain => "www"}
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  require 'json'

  before_filter :authenticate_user!   , :only => [:new, :create, :destroy]
  before_filter :get_course, :only => [:show, :edit, :update, :destroy, :manage]
  before_filter :check_user, :only => [:edit, :update, :destroy, :manage]
  before_filter :get_course_member, :only => [:manage]

  def index
    if signed_in?
      @courses = Course.find_category_abonnements(current_user, true)
      cookies[:categories] = Course.load_user_cookie current_user
    else
      if cookies[:categories].present?
        @courses = Course.set_courses JSON.parse(cookies[:categories])
      else
        cookies[:categories] = Course.set_new_cookie
        @courses = Course.all
      end
    end
    @categories = JSON.parse cookies[:categories]
  end

  def show
    @course_conversation = @course.course_conversations.build
  end

  def show_past_courses
    if signed_in?
      @courses = Course.unscoped.find(:all, :conditions => ["date < ? && user_id = ?",Time.now.to_date, current_user.id ] )
    end
  end

  def new
    @course = Course.new
  end

  def new_with_course
    if course = Course.unscoped.find_by_id(params[:course_id])
      cat = []
      course.categories.map{|f| cat << f.id.to_s }
      @course = Course.new( :title => course.title,
                            :description => course.description,
                            :category_ids => cat,
                            :city => course.city,
                            :places => course.places,
                            :zip_code => course.zip_code,
                            :precognitions => course.precognitions,
                            :materials => course.materials,
                            :country => course.country,
                            :course_request_id => course.course_request_id )
    else
      @course = Course.new
    end
    render :new
  end

  def new_with_request
    if @course_request = CourseRequest.find_by_id(params[:request_id])
      cat = []
      @course_request.categories.map{|f| cat << f.id.to_s }
      @course = Course.new( :title => @course_request.title,
                            :description => @course_request.description,
                            :category_ids => cat,
                            :course_request_id => @course_request.id )
    else
      @course = Course.new
    end
    render :new
  end

  def edit
  end

  def manage
    @course_member_conversation = CourseMemberConversation.new

    if @course_member.present? && cmc = @course_member.course_member_conversations
      cmc.reject{|cmc| cmc.user == current_user}.all?{|c| c.update_attribute(:unread, :false)}
    end
  end

  def create
    @course = current_user.courses.new( params[:course] )
    if @course.valid?
      @course.save!
      flash[:info] = I18n.t('course.create.success')
      @course.provide_course_mailer(current_user)
      if params[:course][:image].blank? || params[:javascript].blank?
        redirect_to course_path(@course)
      else
        render "shared/crop", :locals => {:obj => @course}
      end
    else
      flash_right_error
      render :new
    end
  end

  def update
    @course.update_attributes(params[:course])
    if @course.valid?
      @course.save!
      flash[:info] = I18n.t('course.update.success')
      if params[:course][:image].blank? || params[:javascript].blank?
        redirect_to course_path(@course)
      else
        render "shared/crop", :locals => {:obj => @course}
      end
    else
      flash_right_error
      render :action => :edit
    end
  end

  def destroy
    if Course.delete_course(@course)
      flash[:info] = I18n.t('course.destroy.success')
      redirect_to root_path
    else
      flash[:error] = I18n.t('course.destroy.fail')
      redirect_to course
    end
  end

  private

  def get_course
    unless @course = Course.unscoped.find_by_id(params[:id])
      flash[:error] = I18n.t('msg.not_found')
      redirect_to courses_path and return
    end
  end

  def check_user
    unless @course.user == current_user
      flash[:error] = I18n.t('msg.not_allowed')
      redirect_to courses_path and return
    end
  end

  def get_course_member
    unless params[:course_member_id].nil?
      @course_member = CourseMember.find_by_id(params[:course_member_id])
      unless @course.course_members.include?(@course_member)
        flash[:error] = I18n.t('msg.not_allowed')
        redirect_to courses_path and return
      end
    end
  end

  def flash_right_error
    cat_array = params[:course][:category_ids]
    if cat_array.nil? || cat_array.empty?
      flash[:error] = I18n.t('course.msg.no_categories')
    elsif cat_array.count > 3
      flash[:error] = I18n.t('course.msg.too_much_categories')
    else
      flash[:error] = I18n.t('course.msg.fail')
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper

  def attend_course_link
    (current_user.id != @course.user.id) ? (CourseMember.check_attendance(current_user.id, @course.id)) : true
  end

  def places_available?( course )
    (course.places_available <= 0) ? false : true
  end

  def categories(cat)
    @course ? @course.categories.include?(cat) : false
  end

  def courses_organized(user)
    user.courses_organized_counter
  end

  def courses_attended(user)
    user.courses_attended_counter
  end
end

app/views/courses/_course.html.haml
%article.begegnung
  %a{:href => course_path(course),:class => 'begegnung-pic'}
    = image_tag(coursepic(course, :medium), :alt => course.title, :size => '220x220')
    .begegnung-categories
      - course.categories.each do |cat|
        %span{:class => "cat-#{cat.id}"}
    .clr
    %h3= truncate(course.title, :length => 22, :omission => '..')
  %p.begegnung-infos
    = link_to image_tag(userpic(course.user, :medium), :alt => username(course.user), :size => '60x60'), user_path(course.user)
    = I18n.localize(course.date, :format => :day) unless course.date.nil?
    %br
    = link_to truncate(username(course.user), :length => 18, :omission => '..'), user_path(course.user)
    %br
    = "in #{truncate(course.city, :length => 17, :omission => '..') unless course.city.nil?}"
    %br
    = "#{course.places_available unless course.places_available.nil?} freie Plätze"
  %p.begegnung-text
    = truncate(course.description, :length => 125, :omission => '..')
    %br
    = link_to "Mehr darüber", course_path(course)

app/views/courses/_form.html.haml
= javascript_include_tag 'rails.validations', 'spin'

=form_for @course, :validate => true, :html => {:multipart => true} do |f|
  %fieldset.step-one
    %legend
      %strong Schritt 1 von 2:
      Fakten
			
    %div
      = f.label:title,{:class => 'required'}
      = f.text_field :title

    %div
      = f.label :categories,{:class => 'required'}
      .categories
        - for cat in Category.all
          .category
            = check_box_tag "checkbox_cat-#{cat.id}", "#{cat.id}", categories(cat), :name => "course[category_ids][]", :validate => true
            = label_tag "checkbox_cat-#{cat.id}", cat.title, :class => "checkbox_cat-#{cat.id}"

    %div
      = f.label :date,{:class => 'required'}
      .date-time
        .thedate
          = f.date_select :date, :order => [:day, :month, :year], :include_blank => true, :start_year => Time.now.to_date.year
        .thetime
          um
          = f.time_select :time, {:minute_step => 15, :include_blank => true}
          Uhr

    %div
      = f.label :location,{:class => 'required'}
      .location
        = f.select :country, options_for_select([["Österreich", "AT"], ["Deutschland", "DE"], ["Schweiz", "CH"]], current_user.country)
        PLZ:
        = f.text_field :zip_code, :value => current_user.zip

    %div
      = f.label :places,{:class => 'required'}
      .places
        = f.text_field :places
    .clr

    %div.fieldset-buttons
      %a{:class => 'form-button-petrol form-nextstep right', :id => 'form-nextstep'}
        Weiter zu Schritt 2
        %span

  %fieldset.step-two
    %legend
      %strong Schritt 2 von 2:
      Beschreibung und Foto

    %div
      = f.label :description,{:class => 'required'}
      .description
        = f.text_area :description

    %div
      = f.label :precognitions
      = f.text_area :precognitions

    %div
      = f.label :materials
      = f.text_area :materials

    %div
      = f.label :image
      = f.file_field :image
      -unless @course.image.nil?
        %strong Aktuelles Bild 
        = image_tag coursepic(@course, :thumb)
      %p.small.form-info
        Dein Bild sollte Mindestausmaße von 300x300 px besitzen und im Format JPG oder PNG sein.
			
    = f.hidden_field :course_request_id, :value => @course.course_request_id
    .clr

    .send-button
      %button.form-submit.form-nextstep#form-submit
        Begegnung anbieten
        %span

    .fieldset-buttons{:style => 'float:left'}
      %a{:class => 'form-button-petrol form-laststep left', :id => 'form-laststep'}
        Zurück
        %span

:javascript
  $('form').prepend('#{hidden_field_tag 'javascript', 'true'}')

app/views/courses/crop.html.erb
<% content_for(:head) do %>
<%= stylesheet_link_tag "jquery.Jcrop.min" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 300, 300],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 300/coords.w;
  var ry = 300/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= @course.image_geometry(:original).width %>) + 'px',
    height: Math.round(ry * <%= @course.image_geometry(:original).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= @course.image_geometry(:original).width %> / <%= @course.image_geometry(:big).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag @course.image.url(:big), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:300px; height:300px; overflow:hidden">
  <%= image_tag @course.image.url(:original), :id => "preview" %>
</div>

<%= form_for @course do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "zuschneiden" %></p>
  <div id="send-button" class="send-button">
    <button class="form-submit form-nextstep" id="form-submit">
      Bild zuschneiden
    </button>
    <span></span>
  </div>
<% end %>

app/views/courses/edit.html.haml
%h1 Begegnung bearbeiten
= render :partial => 'form'

app/views/courses/index.de.html.haml
%p.intro Hier kannst du stöbern und eine Begegnung finden, bei der du etwas ganz Neues erlernen und gleichzeitig interessante Menschen kennen lernen kannst. Du hast etwas, das du gerne anderen beibringen möchtest? Dann erstelle doch deine eigene Begegnung.

%section.begegnungssearch
  = render :partial => '/shared/search', :locals => {:categories => @categories}

%section.begegnungen

  =render 'shared/begegnung'
  #courses_div
    = render :partial => 'course', :collection => @courses
  =render 'shared/begegnung_new'

app/views/courses/manage.de.html.haml
%section.detail
  = render :partial => '/courses/manage/sidebar', :locals => { :course => @course }
  %article.main
    %h1 Begegnung Verwalten

    %section.course-member-main
      -unless @course_member.nil?
        = render(:partial => '/course_member_conversations/course_member_message', :collection => @course_member.course_member_conversations) || "keine"
        %br
        %h2 Neue Antwort:
        = render :partial => '/course_member_conversations/form', :locals => { :cmc => @course_member_conversation, :course => @course_member.course, :form_path => :host_reply_course_member_conversations, :button_text => "Antworten"}
        = render :partial => '/course_members/buttons/buttons', :locals => {:course_member => @course_member}
      -else
        %h2 Wähle bitte einen der bisherigen Anfragen um diese zu verwalten!

app/views/courses/new.html.haml
%h1 Neue Begegnung
= render :partial => 'form'

app/views/courses/show.de.html.haml
%section.detail
  %article.main
    %h3= @course.categories.collect { |r| r.title }.join( ' • ' )
    %h1= @course.title
    = render :partial => '/shared/social_media_like_buttons', :locals => { :special_url => request.original_url}
    %p= simple_format (@course.description)
    %h2 Benötigte Vorkenntnisse
    %p= simple_format (@course.precognitions.blank? ? "keine" : @course.precognitions)
    %h2 Mitzubringendes Material
    %p= simple_format (@course.materials.blank? ? "keine" : @course.materials)

    %br
    -if signed_in? && @course.course_members.find_by_user_id_and_accepted(current_user.id, 1)
      =render :partial => '/courses/show/conversations', :locals => { :course => @course, :conversation => @course_conversation }

  %article.side
    %figure.fancyimg
      %a{:href => coursepic(@course, :big), :class => 'pic', :rel => 'alternate'}
        = image_tag(coursepic(@course, :medium), :alt => @course.title, :size => '300x300')
        %span
    .clr
    %ul.facts
      %li.date
        %span
        = I18n.localize(@course.date, :format => :day) unless @course.date.nil?
      %li.time
        %span
        = I18n.localize(@course.time, :format => :time) unless @course.time.nil?
      %li.location
        %span
        = @course.city unless @course.city.nil?
      %li.people
        %span
        = "für #{@course.places} Personen" unless @course.places.nil?
    .clr
    %br
    .begegnung-host.small
      = link_to image_tag(userpic(@course.user, :medium), :alt => username(@course.user), :size => '100x100'), user_path(@course.user)
      %h4= link_to username(@course.user), user_path(@course.user)
      %p.host-description
        = truncate(@course.user.description, :length => 65, :omission => '..') unless @course.user.description.nil?
        = link_to "Profil ansehen", user_path(@course.user)
      .host-interaction
        = link_to "Profil ansehen", user_path(@course.user), :class => 'button-profil'

        = form_tag(new_user_conversation_path, :method => :post) do
          = hidden_field_tag :recipient_id, @course.user.id
          %button.button-message
            Nachricht senden


    %p
      - if signed_in?
        -if @course.user == current_user
          -if @course.date > Time.now
            %a{:href => url_for(edit_course_path(@course)), :class => 'form-button-petrol form-nextstep'}
              Begegnung ändern
              %span
            %br
            %a{:href => url_for(manage_course_path(@course)), :class => 'form-submit form-nextstep'}
              Verwalten
              %span
            %br
            =link_to "Begegnung absagen", course_path(@course), :method => :delete,:class => 'form-button-petrol form-nextstep', :confirm => "Wollen Sie den Kurs wirklich absagen?"
          -else
            = form_tag({:controller => :courses, :action => :new_with_course}, :method => :post) do
              = hidden_field_tag :course_id, @course.id
              %button.form-submit.form-nextstep{:style => 'width: 100%'}
                Erneut anbieten
                %span

        - else
          -if @course_member = CourseMember.find_by_course_id_and_user_id(@course.id, current_user.id)
            = link_to "Teilnahme verwalten", course_member_path(@course_member), :class => 'form-next-step form-submit'
          -else
            -if places_available?( @course )
              = form_tag(new_request_course_members_path, :method => :post) do
                = hidden_field_tag 'course_id', @course.id
                %button.form-submit.form-nextstep{:style => 'width: 100%'}
                  Teilnahme anfragen
                  %span
      - else
        -if places_available?( @course )
          = form_tag(new_request_course_members_path, :method => :post) do
            = hidden_field_tag 'course_id', @course.id
            %button.form-submit.form-nextstep{:style => 'width: 100%'}
              Teilnahme anfragen
              %span
      = form_tag(new_user_conversation_path, :method => :post) do
        = hidden_field_tag :recipient_id, 0
        = hidden_field_tag :subject, "User: #{@course.user.first_name} mit der id #{@course.user.id}"
        = hidden_field_tag :body, "User hat die Begegnung #{@course.title} mit der id #{@course.id} erstellt. Die Begegnung enthält folgende auffällige Inhalte:"
        %button.form-button-petrol.form-submit{:style => 'width: 36px; height: 36px; font-size: 24px; line-height: 30px; margin-top: 10px', :onclick => "return confirm('Willst du diese Begegnung wirklich melden?')" }
          !
          %span

app/views/courses/show_past_courses.de.html.haml
%section.detail
  %article.main
    .user-courses
      %h2 Vergangene Begegnungen
      -@courses.each do |course|
        %article.begegnung.left
          %section.description
            %h2= link_to truncate(course.title, :length => 17, :omission => '..'), course_path(course)
            %p= I18n.localize(course.date, :format => :day) unless course.date.nil?
            %p= "in #{truncate(course.city, :length => 17, :omission => '..') unless course.city.nil?}"
          = link_to image_tag(coursepic(course, :xsmall), :size => '100x100'), course_path(course)

        = form_tag({:controller => :courses, :action => :new_with_course}, :method => :post) do
          = hidden_field_tag :course_id, course.id
          %button.form-submit.form-nextstep{:style => 'width: 100%'}
            Erneut anbieten
            %span

        %br
        .clr